version:
services:
  adminer:
    image: adminer
    ports:
      - 8080:8080
  mydb:
    image: postgres
    environment:
      POSTGRES_PASSWORD: king2128
      POSTGRES_USER: myuser
      POSTGRES_DB: mydb   